In [1]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualización
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# Evaluar linealidad de las relaciones entre las variables
# ------------------------------------------------------------------------------
from scipy.stats import shapiro, kstest

# Configuración
# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# Gestión de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

# CREACION DE LOS DF

In [2]:
eventos = pd.read_csv('eventos_2025.csv')
facturacion = pd.read_csv('facturacion_2025.csv')
precios_habs = pd.read_csv('precios_habs_2025.csv')
congresos = pd.read_csv('congresos_2025.csv')

# EDA

## DF EVENTOS

In [3]:
eventos.head()

,producto,id_booking,estado,fecha_inicio,fecha_fin,fecha_creacion,cliente
0,Salas,7385,Perdido,2025-01-15,2025-01-16,2024-02-19,"GENERICO, EMPRESAS"
1,Habs y Salas,7983,Cancelado,2025-01-17,2025-01-19,2024-03-07,"GENERICO, AGENCIAS"
2,Habs y Salas,8973,Perdido,2025-03-12,2025-03-16,2024-04-10,"GENERICO, AGENCIAS"
3,Habs y Salas,9151,Perdido,2025-03-16,2025-03-22,2024-04-17,"GENERICO, EMPRESAS"
4,Habs y Salas,9265,Rechazado,2025-03-11,2025-03-14,2024-04-22,"GENERICO, AGENCIAS"

In [4]:
eventos.info()

<class 'pandas.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   producto        676 non-null    str
 1   id_booking      676 non-null    int64
 2   estado          676 non-null    str
 3   fecha_inicio    676 non-null    str
 4   fecha_fin       676 non-null    str
 5   fecha_creacion  676 non-null    str
 6   cliente         676 non-null    str
dtypes: int64(1), str(6)
memory usage: 78.0 KB

In [71]:
#En la informacion del df de eventos podemos observar que no tenemos nulos y que todas las columnas son strings excepto el id_booking.
#CAMBIAMOS TAMBIEN EL DYTYPE DE FECHAS

In [6]:
eventos['fecha_inicio'] = pd.to_datetime(eventos['fecha_inicio'])
eventos['fecha_fin'] = pd.to_datetime(eventos['fecha_fin'])
eventos['fecha_creacion'] = pd.to_datetime(eventos['fecha_creacion'])

In [7]:
eventos.info()

<class 'pandas.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   producto        676 non-null    str
 1   id_booking      676 non-null    int64
 2   estado          676 non-null    str
 3   fecha_inicio    676 non-null    datetime64[us]
 4   fecha_fin       676 non-null    datetime64[us]
 5   fecha_creacion  676 non-null    datetime64[us]
 6   cliente         676 non-null    str
dtypes: datetime64[us](3), int64(1), str(3)
memory usage: 58.2 KB

In [8]:
eventos.shape

(676, 7)

In [9]:
eventos.describe().T

,count,mean,min,25%,50%,75%,max,std
id_booking,676.0,22921.211538,7385.0,18683.75,22856.5,28292.0,31180.0,5563.099619
fecha_inicio,676,2025-07-25 23:49:20.946745,2025-01-03 00:00:00,2025-04-12 00:00:00,2025-07-26 12:00:00,2025-11-14 00:00:00,2025-12-27 00:00:00,NaN
fecha_fin,676,2025-07-28 15:01:03.905325,2025-01-07 00:00:00,2025-04-16 18:00:00,2025-08-03 12:00:00,2025-11-15 00:00:00,2025-12-27 00:00:00,NaN
fecha_creacion,676,2025-05-12 14:46:09.230769,2024-02-19 00:00:00,2025-01-27 00:00:00,2025-05-01 00:00:00,2025-10-05 06:00:00,2025-12-26 00:00:00,NaN

In [10]:
eventos.describe(include='object').T

         count unique                top freq
producto   676      2              Salas  456
estado     676      4            Perdido  376
cliente    676    124  GENERICO GENERICO  252

In [11]:
eventos.isnull().sum()

producto          0
id_booking        0
estado            0
fecha_inicio      0
fecha_fin         0
fecha_creacion    0
cliente           0
dtype: int64

In [12]:
eventos.duplicated().sum()

np.int64(0)

## DF FACTURACION

In [13]:
facturacion.head()

,id_booking,Nombre_Cliente,Fecha_inicio,Tipo_evento,Pax,Total_evento,Sala,FB,Alojamiento,Extras
0,NaN,cliente_001,2025-02-22 00:00:00,BANQUETE,19,786.38,0.00,786.38,0.0,0.0
1,NaN,cliente_002,2025-05-10 00:00:00,BANQUETE,19,576.93,0.00,576.93,0.0,0.0
2,NaN,cliente_003,2025-04-21 00:00:00,BANQUETE,11,455.27,0.00,455.27,0.0,0.0
3,NaN,cliente_004,2025-10-24 00:00:00,REUNIÓN,15,0.00,0.00,0.00,0.0,0.0
4,NaN,cliente_005,2025-03-15 00:00:00,BANQUETE,14,438.97,25.08,413.89,0.0,0.0

In [14]:
# Con la primera visualizacion de los datos podemos ver que tenemos nulos por ahora en id_booking, que la fecha de inicio pdriamos borrar la hora ya que son todas igual y que pendiente revisar las columnas alojamiento y extras. 
# tambien poner todos los nombres en minuscula como el df de eventos

In [15]:
facturacion['Fecha_inicio'] = pd.to_datetime(facturacion['Fecha_inicio'])

In [16]:
facturacion.head()

,id_booking,Nombre_Cliente,Fecha_inicio,Tipo_evento,Pax,Total_evento,Sala,FB,Alojamiento,Extras
0,NaN,cliente_001,2025-02-22,BANQUETE,19,786.38,0.00,786.38,0.0,0.0
1,NaN,cliente_002,2025-05-10,BANQUETE,19,576.93,0.00,576.93,0.0,0.0
2,NaN,cliente_003,2025-04-21,BANQUETE,11,455.27,0.00,455.27,0.0,0.0
3,NaN,cliente_004,2025-10-24,REUNIÓN,15,0.00,0.00,0.00,0.0,0.0
4,NaN,cliente_005,2025-03-15,BANQUETE,14,438.97,25.08,413.89,0.0,0.0

In [17]:
facturacion.info()

<class 'pandas.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_booking      242 non-null    float64
 1   Nombre_Cliente  265 non-null    str
 2   Fecha_inicio    265 non-null    datetime64[us]
 3   Tipo_evento     265 non-null    str
 4   Pax             265 non-null    int64
 5   Total_evento    265 non-null    float64
 6   Sala            265 non-null    float64
 7   FB              265 non-null    float64
 8   Alojamiento     265 non-null    float64
 9   Extras          265 non-null    float64
dtypes: datetime64[us](1), float64(6), int64(1), str(2)
memory usage: 25.7 KB

In [18]:
facturacion['Alojamiento'].value_counts()
#Con el value_counts podemos ver que no es una columna que solo contenga 0, sino que son los eventos que no tienen alojamiento

Alojamiento
0.00        222
16549.04      1
9199.06       1
49138.21      1
843.26        1
802.69        1
5509.70       1
1267.37       1
30315.64      1
5795.72       1
10952.55      1
4880.72       1
2661.66       1
4249.23       1
5914.81       1
884.21        1
14114.83      1
1806.05       1
4336.97       1
4037.27       1
1197.13       1
3509.94       1
1755.88       1
4744.64       1
6615.90       1
139.22        1
282.20        1
2993.52       1
2078.84       1
4515.12       1
453.77        1
4791.04       1
107.23        1
9737.61       1
4159.55       1
7129.27       1
188.76        1
3693.62       1
2234.98       1
3292.28       1
3226.43       1
1309.38       1
1501.28       1
233.28        1
Name: count, dtype: int64

In [19]:
facturacion['Extras'].value_counts()
#En la columna nos muestra algo mas de informacion que no sabes que es asi que para el analsisi es irrelevante, pero no la borramos porque sino el total no concuerda

Extras
0.00       251
7.53         5
147.37       1
3235.33      1
766.38       1
17.56        1
67.73        1
31.36        1
16.30        1
50.17        1
78.39        1
Name: count, dtype: int64

In [20]:
facturacion.columns = facturacion.columns.str.lower()

In [21]:
facturacion.head()

,id_booking,nombre_cliente,fecha_inicio,tipo_evento,pax,total_evento,sala,fb,alojamiento,extras
0,NaN,cliente_001,2025-02-22,BANQUETE,19,786.38,0.00,786.38,0.0,0.0
1,NaN,cliente_002,2025-05-10,BANQUETE,19,576.93,0.00,576.93,0.0,0.0
2,NaN,cliente_003,2025-04-21,BANQUETE,11,455.27,0.00,455.27,0.0,0.0
3,NaN,cliente_004,2025-10-24,REUNIÓN,15,0.00,0.00,0.00,0.0,0.0
4,NaN,cliente_005,2025-03-15,BANQUETE,14,438.97,25.08,413.89,0.0,0.0

### Gestion de nulos

In [22]:
#Como estoy familiarizada con los datos y como se llegan a guardar en el sistema SAP, se que los eventos se pueden integrar de la manera antigua (nº de evento) y de la manera nueva que es con booking file. Esta nueva manera tiene nº de evento y booking file. De tal manera que estos nulos directamente les creamos un id nuevo (que no estará en el df de eventos porque esta sacado de booking file)

In [23]:
#miramos primero que numeros tenemos ya ocupados de los dos df

In [24]:
facturacion['id_booking'].min()

np.float64(9612.0)

In [25]:
facturacion['id_booking'].max()

np.float64(31180.0)

In [26]:
eventos['id_booking'].min()

np.int64(7385)

In [27]:
eventos['id_booking'].max()

np.int64(31180)

In [28]:
nulos = facturacion['id_booking'].isna()
facturacion.loc[nulos, 'id_booking'] = range(1, nulos.sum() + 1)

In [29]:
facturacion['id_booking'].unique()

array([1.0000e+00, 2.0000e+00, 3.0000e+00, 4.0000e+00, 5.0000e+00,
       6.0000e+00, 9.6120e+03, 9.6760e+03, 1.1786e+04, 1.3064e+04,
       1.3106e+04, 1.3233e+04, 1.0634e+04, 1.3844e+04, 1.3912e+04,
       1.4203e+04, 1.4814e+04, 1.5088e+04, 1.5122e+04, 1.5077e+04,
       1.5482e+04, 1.5500e+04, 1.5666e+04, 1.5721e+04, 1.5722e+04,
       1.5737e+04, 1.6314e+04, 1.6414e+04, 1.6434e+04, 1.6732e+04,
       1.7024e+04, 1.7426e+04, 1.7428e+04, 1.7429e+04, 1.7529e+04,
       1.7735e+04, 1.7737e+04, 1.7879e+04, 1.7954e+04, 1.7946e+04,
       1.7933e+04, 1.8000e+04, 1.8001e+04, 1.8002e+04, 1.8003e+04,
       1.8004e+04, 1.8201e+04, 1.8205e+04, 1.8360e+04, 1.8350e+04,
       1.8408e+04, 1.8437e+04, 1.8439e+04, 1.8440e+04, 1.8451e+04,
       1.8456e+04, 1.8458e+04, 1.8503e+04, 1.8665e+04, 1.8695e+04,
       1.8696e+04, 1.8697e+04, 1.8698e+04, 1.8699e+04, 1.8700e+04,
       1.8825e+04, 1.9037e+04, 1.9038e+04, 1.9040e+04, 1.9101e+04,
       1.9093e+04, 1.9119e+04, 1.9276e+04, 1.9597e+04, 1.9598e+04,
       1.9600e+04, 1.9741e+04, 1.9775e+04, 1.9778e+04, 1.9779e+04,
       2.0114e+04, 2.0115e+04, 2.0116e+04, 2.0117e+04, 2.0173e+04,
       2.0648e+04, 2.0699e+04, 2.0816e+04, 2.0844e+04, 2.0891e+04,
       2.1044e+04, 2.1020e+04, 2.1322e+04, 2.1563e+04, 2.1564e+04,
       2.1575e+04, 2.1663e+04, 2.1737e+04, 2.1882e+04, 2.1891e+04,
       2.1957e+04, 2.2111e+04, 2.2116e+04, 2.2210e+04, 2.2324e+04,
       2.2365e+04, 2.2366e+04, 2.2417e+04, 2.2421e+04, 2.2422e+04,
       2.2444e+04, 2.2501e+04, 2.2591e+04, 2.2657e+04, 2.2718e+04,
       2.2790e+04, 2.2821e+04, 2.2892e+04, 2.2937e+04, 2.2955e+04,
       2.3167e+04, 2.3226e+04, 2.3227e+04, 2.3295e+04, 2.3329e+04,
       2.3426e+04, 2.3449e+04, 2.3510e+04, 2.3556e+04, 2.3632e+04,
       2.3806e+04, 2.3807e+04, 2.4003e+04, 2.4010e+04, 2.4041e+04,
       2.4255e+04, 2.4509e+04, 1.9994e+04, 2.4593e+04, 2.4594e+04,
       2.4696e+04, 2.4966e+04, 2.5148e+04, 2.5481e+04, 2.5656e+04,
       2.6064e+04, 2.6400e+04, 2.6809e+04, 2.6892e+04, 2.6893e+04,
       2.6946e+04, 2.6962e+04, 2.7015e+04, 2.7285e+04, 2.7319e+04,
       2.7353e+04, 2.7359e+04, 2.7533e+04, 2.7558e+04, 2.7857e+04,
       2.7904e+04, 2.7907e+04, 2.7991e+04, 2.8101e+04, 2.8103e+04,
       2.8104e+04, 2.8105e+04, 2.8106e+04, 2.8151e+04, 2.8325e+04,
       2.8315e+04, 2.8342e+04, 2.8309e+04, 2.8377e+04, 2.8422e+04,
       2.8410e+04, 2.8448e+04, 2.8457e+04, 2.8458e+04, 2.8501e+04,
       2.8541e+04, 2.8593e+04, 2.8705e+04, 2.8707e+04, 2.8692e+04,
       2.8679e+04, 2.8710e+04, 2.8837e+04, 2.8942e+04, 2.8944e+04,
       2.8959e+04, 2.9016e+04, 2.9072e+04, 2.9058e+04, 2.9104e+04,
       2.9169e+04, 2.9170e+04, 2.9191e+04, 2.9195e+04, 2.9203e+04,
       2.9284e+04, 2.9293e+04, 2.9327e+04, 2.9513e+04, 2.9509e+04,
       2.9510e+04, 2.9522e+04, 2.9559e+04, 2.9591e+04, 2.9579e+04,
       2.9611e+04, 2.9612e+04, 2.9671e+04, 2.9803e+04, 2.9804e+04,
       2.9774e+04, 2.9778e+04, 2.9899e+04, 2.9978e+04, 2.9979e+04,
       2.9980e+04, 3.0010e+04, 3.0070e+04, 3.0080e+04, 3.0116e+04,
       3.0145e+04, 3.0147e+04, 3.0149e+04, 3.0292e+04, 3.0332e+04,
       3.0334e+04, 3.0336e+04, 3.0337e+04, 3.0449e+04, 3.0465e+04,
       3.0466e+04, 3.0486e+04, 3.0476e+04, 3.0531e+04, 3.0578e+04,
       3.0681e+04, 3.0691e+04, 3.0692e+04, 3.0693e+04, 3.0694e+04,
       3.0780e+04, 3.0910e+04, 3.1180e+04, 7.0000e+00, 8.0000e+00,
       9.0000e+00, 1.0000e+01, 1.1000e+01, 1.2000e+01, 1.3000e+01,
       1.4000e+01, 1.5000e+01, 1.6000e+01, 1.7000e+01, 1.8000e+01,
       1.9000e+01, 2.0000e+01, 2.1000e+01, 2.2000e+01, 2.3000e+01])

In [30]:
facturacion.info()

<class 'pandas.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_booking      265 non-null    float64
 1   nombre_cliente  265 non-null    str
 2   fecha_inicio    265 non-null    datetime64[us]
 3   tipo_evento     265 non-null    str
 4   pax             265 non-null    int64
 5   total_evento    265 non-null    float64
 6   sala            265 non-null    float64
 7   fb              265 non-null    float64
 8   alojamiento     265 non-null    float64
 9   extras          265 non-null    float64
dtypes: datetime64[us](1), float64(6), int64(1), str(2)
memory usage: 25.7 KB

In [31]:
facturacion['id_booking'] = facturacion['id_booking'].astype(int)

In [32]:
facturacion.info()

<class 'pandas.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_booking      265 non-null    int64
 1   nombre_cliente  265 non-null    str
 2   fecha_inicio    265 non-null    datetime64[us]
 3   tipo_evento     265 non-null    str
 4   pax             265 non-null    int64
 5   total_evento    265 non-null    float64
 6   sala            265 non-null    float64
 7   fb              265 non-null    float64
 8   alojamiento     265 non-null    float64
 9   extras          265 non-null    float64
dtypes: datetime64[us](1), float64(5), int64(2), str(2)
memory usage: 25.7 KB

In [33]:
facturacion['id_booking'].unique()

array([    1,     2,     3,     4,     5,     6,  9612,  9676, 11786,
       13064, 13106, 13233, 10634, 13844, 13912, 14203, 14814, 15088,
       15122, 15077, 15482, 15500, 15666, 15721, 15722, 15737, 16314,
       16414, 16434, 16732, 17024, 17426, 17428, 17429, 17529, 17735,
       17737, 17879, 17954, 17946, 17933, 18000, 18001, 18002, 18003,
       18004, 18201, 18205, 18360, 18350, 18408, 18437, 18439, 18440,
       18451, 18456, 18458, 18503, 18665, 18695, 18696, 18697, 18698,
       18699, 18700, 18825, 19037, 19038, 19040, 19101, 19093, 19119,
       19276, 19597, 19598, 19600, 19741, 19775, 19778, 19779, 20114,
       20115, 20116, 20117, 20173, 20648, 20699, 20816, 20844, 20891,
       21044, 21020, 21322, 21563, 21564, 21575, 21663, 21737, 21882,
       21891, 21957, 22111, 22116, 22210, 22324, 22365, 22366, 22417,
       22421, 22422, 22444, 22501, 22591, 22657, 22718, 22790, 22821,
       22892, 22937, 22955, 23167, 23226, 23227, 23295, 23329, 23426,
       23449, 23510, 23556, 23632, 23806, 23807, 24003, 24010, 24041,
       24255, 24509, 19994, 24593, 24594, 24696, 24966, 25148, 25481,
       25656, 26064, 26400, 26809, 26892, 26893, 26946, 26962, 27015,
       27285, 27319, 27353, 27359, 27533, 27558, 27857, 27904, 27907,
       27991, 28101, 28103, 28104, 28105, 28106, 28151, 28325, 28315,
       28342, 28309, 28377, 28422, 28410, 28448, 28457, 28458, 28501,
       28541, 28593, 28705, 28707, 28692, 28679, 28710, 28837, 28942,
       28944, 28959, 29016, 29072, 29058, 29104, 29169, 29170, 29191,
       29195, 29203, 29284, 29293, 29327, 29513, 29509, 29510, 29522,
       29559, 29591, 29579, 29611, 29612, 29671, 29803, 29804, 29774,
       29778, 29899, 29978, 29979, 29980, 30010, 30070, 30080, 30116,
       30145, 30147, 30149, 30292, 30332, 30334, 30336, 30337, 30449,
       30465, 30466, 30486, 30476, 30531, 30578, 30681, 30691, 30692,
       30693, 30694, 30780, 30910, 31180,     7,     8,     9,    10,
          11,    12,    13,    14,    15,    16,    17,    18,    19,
          20,    21,    22,    23])

## DF PRECIOS HABS

In [34]:
precios_habs.head()

   Unnamed: 0         dia  precio  pct_ocupacion
0           0  2025-01-01     140          86.29
1           1  2025-01-02     140          76.61
2           2  2025-01-03     110          62.10
3           3  2025-01-04     110          53.23
4           4  2025-01-05     110          66.94

In [35]:
#primero podemos eliminar el indice doble y cambiar el nombre de la columna dia por fecha

In [36]:
precios_habs = precios_habs.drop(columns='Unnamed: 0')

In [37]:
precios_habs.head()

          dia  precio  pct_ocupacion
0  2025-01-01     140          86.29
1  2025-01-02     140          76.61
2  2025-01-03     110          62.10
3  2025-01-04     110          53.23
4  2025-01-05     110          66.94

In [38]:
precios_habs = precios_habs.rename(columns={'dia': 'fecha'})

In [39]:
precios_habs.info()

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fecha          365 non-null    str
 1   precio         365 non-null    int64
 2   pct_ocupacion  365 non-null    float64
dtypes: float64(1), int64(1), str(1)
memory usage: 12.2 KB

In [40]:
precios_habs['fecha'] = pd.to_datetime(precios_habs['fecha'])

In [41]:
precios_habs.info()

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fecha          365 non-null    datetime64[us]
 1   precio         365 non-null    int64
 2   pct_ocupacion  365 non-null    float64
dtypes: datetime64[us](1), float64(1), int64(1)
memory usage: 8.7 KB

In [42]:
precios_habs.head()

       fecha  precio  pct_ocupacion
0 2025-01-01     140          86.29
1 2025-01-02     140          76.61
2 2025-01-03     110          62.10
3 2025-01-04     110          53.23
4 2025-01-05     110          66.94

## DF CONGRESOS

In [43]:
congresos.head()

        evento fecha_inicio   fecha_fin
0          ICE   19/01/2025  22/01/2025
1          ISE   04/02/2025  07/02/2025
2  Maraton BCN   16/02/2025  16/02/2025
3          MWC   02/03/2025  06/03/2025
4  Maraton BCN   16/03/2025  16/03/2025

In [44]:
congresos.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   evento        31 non-null     str
 1   fecha_inicio  31 non-null     str
 2   fecha_fin     31 non-null     str
dtypes: str(3)
memory usage: 1.7 KB

In [45]:
#cambiamos el dtype a fecha

In [46]:
congresos['fecha_inicio'] = pd.to_datetime(congresos['fecha_inicio'])

In [47]:
congresos['fecha_fin'] = pd.to_datetime(congresos['fecha_fin'])

In [48]:
congresos

             evento fecha_inicio  fecha_fin
0               ICE   2025-01-19 2025-01-22
1               ISE   2025-02-04 2025-02-07
2       Maraton BCN   2025-02-16 2025-02-16
3               MWC   2025-03-02 2025-03-06
4       Maraton BCN   2025-03-16 2025-03-16
5              EWNA   2025-03-25 2025-03-28
6        Sem. Santa   2025-04-17 2025-04-21
7       Bridal Week   2025-04-22 2025-04-25
8            IVIRMA   2025-04-24 2025-04-26
9           SEAFOOD   2025-05-05 2025-05-08
10              IOT   2025-05-12 2025-05-15
11        VITAFOODS   2025-05-19 2025-05-23
12       CONSTRUMAT   2025-05-20 2025-05-22
13               F1   2025-05-30 2025-06-01
14  Primavera Sound   2025-06-05 2025-06-08
15            EULAR   2025-06-10 2025-06-15
16             IADR   2025-06-25 2025-06-28
17             WCLC   2025-09-05 2025-09-09
18          Moto GP   2025-09-05 2025-09-07
19        LABELEXPO   2025-09-15 2025-09-19
20         BIOSPAIN   2025-09-15 2025-09-18
21          ECTRIMS   2025-09-22 2025-09-27
22            IAAPA   2025-09-22 2025-09-25
23        SMARTCITY   2025-11-03 2025-11-06
24           VMware   2025-11-04 2025-11-06
25          GARTNER   2025-11-09 2025-11-13
26             IBTM   2025-11-17 2025-11-23
27               HP   2025-11-17 2025-11-23
28            MIFAS   2025-11-17 2025-11-23
29    Work Day Rise   2025-11-17 2025-11-21
30     Sal. piscina   2025-11-17 2025-11-21

# UNION Y LIMPIEZA

In [49]:
#junto el df de eventos y por facturacion por `id_booking` para ver de golpe qué peticiones se ganaron y cuánto facturó cada una.
# Uso how='outer' para no perder nada: ni las peticiones perdidas, ni los 23 eventos metidos sin booking file

In [50]:
df = eventos.merge(facturacion, on='id_booking', how='outer')

In [51]:
print(df.shape)

(699, 16)

In [52]:
df.head()

,producto,id_booking,estado,fecha_inicio_x,fecha_fin,fecha_creacion,cliente,nombre_cliente,fecha_inicio_y,tipo_evento,pax,total_evento,sala,fb,alojamiento,extras
0,NaN,1,NaN,NaT,NaT,NaT,NaN,cliente_001,2025-02-22,BANQUETE,19.0,786.38,0.00,786.38,0.0,0.0
1,NaN,2,NaN,NaT,NaT,NaT,NaN,cliente_002,2025-05-10,BANQUETE,19.0,576.93,0.00,576.93,0.0,0.0
2,NaN,3,NaN,NaT,NaT,NaT,NaN,cliente_003,2025-04-21,BANQUETE,11.0,455.27,0.00,455.27,0.0,0.0
3,NaN,4,NaN,NaT,NaT,NaT,NaN,cliente_004,2025-10-24,REUNIÓN,15.0,0.00,0.00,0.00,0.0,0.0
4,NaN,5,NaN,NaT,NaT,NaT,NaN,cliente_005,2025-03-15,BANQUETE,14.0,438.97,25.08,413.89,0.0,0.0

In [53]:
df['fecha_inicio'] = df['fecha_inicio_x'].fillna(df['fecha_inicio_y'])
df['cliente'] = df['cliente'].fillna(df['nombre_cliente'])
df = df.drop(columns=['fecha_inicio_x', 'fecha_inicio_y', 'nombre_cliente'])

In [54]:
df.head()

,producto,id_booking,estado,fecha_fin,fecha_creacion,cliente,tipo_evento,pax,total_evento,sala,fb,alojamiento,extras,fecha_inicio
0,NaN,1,NaN,NaT,NaT,cliente_001,BANQUETE,19.0,786.38,0.00,786.38,0.0,0.0,2025-02-22
1,NaN,2,NaN,NaT,NaT,cliente_002,BANQUETE,19.0,576.93,0.00,576.93,0.0,0.0,2025-05-10
2,NaN,3,NaN,NaT,NaT,cliente_003,BANQUETE,11.0,455.27,0.00,455.27,0.0,0.0,2025-04-21
3,NaN,4,NaN,NaT,NaT,cliente_004,REUNIÓN,15.0,0.00,0.00,0.00,0.0,0.0,2025-10-24
4,NaN,5,NaN,NaT,NaT,cliente_005,BANQUETE,14.0,438.97,25.08,413.89,0.0,0.0,2025-03-15

In [55]:
df = df[['id_booking', 'fecha_inicio', 'producto', 'estado', 'cliente',
         'fecha_fin', 'fecha_creacion', 'tipo_evento', 'pax',
         'total_evento', 'sala', 'fb', 'alojamiento']]

In [56]:
df.head()

,id_booking,fecha_inicio,producto,estado,cliente,fecha_fin,fecha_creacion,tipo_evento,pax,total_evento,sala,fb,alojamiento
0,1,2025-02-22,NaN,NaN,cliente_001,NaT,NaT,BANQUETE,19.0,786.38,0.00,786.38,0.0
1,2,2025-05-10,NaN,NaN,cliente_002,NaT,NaT,BANQUETE,19.0,576.93,0.00,576.93,0.0
2,3,2025-04-21,NaN,NaN,cliente_003,NaT,NaT,BANQUETE,11.0,455.27,0.00,455.27,0.0
3,4,2025-10-24,NaN,NaN,cliente_004,NaT,NaT,REUNIÓN,15.0,0.00,0.00,0.00,0.0
4,5,2025-03-15,NaN,NaN,cliente_005,NaT,NaT,BANQUETE,14.0,438.97,25.08,413.89,0.0

In [57]:
df.tail()

,id_booking,fecha_inicio,producto,estado,cliente,fecha_fin,fecha_creacion,tipo_evento,pax,total_evento,sala,fb,alojamiento
694,30700,2025-12-17,Salas,Perdido,"GENERICO, AGENCIAS",2025-12-17,2025-12-09,NaN,NaN,NaN,NaN,NaN,NaN
695,30766,2025-12-16,Salas,Perdido,GENERICO GENERICO,2025-12-16,2025-12-11,NaN,NaN,NaN,NaN,NaN,NaN
696,30780,2025-12-13,Salas,CONFIRMACIÓN,GENERICO GENERICO,2025-12-13,2025-12-10,COCKTAIL,130.0,0.00,0.00,0.0,0.0
697,30910,2025-12-24,Salas,CONFIRMACIÓN,cliente_120,2025-12-24,2025-12-16,BANQUETE,20.0,790.15,790.15,0.0,0.0
698,31180,2025-12-26,Salas,CONFIRMACIÓN,cliente_121,2025-12-26,2025-12-26,BANQUETE,38.0,1584.44,1584.44,0.0,0.0

In [58]:
df[['total_evento','sala','fb','alojamiento']] = df[['total_evento','sala','fb','alojamiento']].fillna(0)

In [59]:
df.head()

,id_booking,fecha_inicio,producto,estado,cliente,fecha_fin,fecha_creacion,tipo_evento,pax,total_evento,sala,fb,alojamiento
0,1,2025-02-22,NaN,NaN,cliente_001,NaT,NaT,BANQUETE,19.0,786.38,0.00,786.38,0.0
1,2,2025-05-10,NaN,NaN,cliente_002,NaT,NaT,BANQUETE,19.0,576.93,0.00,576.93,0.0
2,3,2025-04-21,NaN,NaN,cliente_003,NaT,NaT,BANQUETE,11.0,455.27,0.00,455.27,0.0
3,4,2025-10-24,NaN,NaN,cliente_004,NaT,NaT,REUNIÓN,15.0,0.00,0.00,0.00,0.0
4,5,2025-03-15,NaN,NaN,cliente_005,NaT,NaT,BANQUETE,14.0,438.97,25.08,413.89,0.0

In [60]:
df.tail()

,id_booking,fecha_inicio,producto,estado,cliente,fecha_fin,fecha_creacion,tipo_evento,pax,total_evento,sala,fb,alojamiento
694,30700,2025-12-17,Salas,Perdido,"GENERICO, AGENCIAS",2025-12-17,2025-12-09,NaN,NaN,0.00,0.00,0.0,0.0
695,30766,2025-12-16,Salas,Perdido,GENERICO GENERICO,2025-12-16,2025-12-11,NaN,NaN,0.00,0.00,0.0,0.0
696,30780,2025-12-13,Salas,CONFIRMACIÓN,GENERICO GENERICO,2025-12-13,2025-12-10,COCKTAIL,130.0,0.00,0.00,0.0,0.0
697,30910,2025-12-24,Salas,CONFIRMACIÓN,cliente_120,2025-12-24,2025-12-16,BANQUETE,20.0,790.15,790.15,0.0,0.0
698,31180,2025-12-26,Salas,CONFIRMACIÓN,cliente_121,2025-12-26,2025-12-26,BANQUETE,38.0,1584.44,1584.44,0.0,0.0

In [61]:
df['producto'] = df['producto'].fillna('Salas')

In [62]:
df.head()

,id_booking,fecha_inicio,producto,estado,cliente,fecha_fin,fecha_creacion,tipo_evento,pax,total_evento,sala,fb,alojamiento
0,1,2025-02-22,Salas,NaN,cliente_001,NaT,NaT,BANQUETE,19.0,786.38,0.00,786.38,0.0
1,2,2025-05-10,Salas,NaN,cliente_002,NaT,NaT,BANQUETE,19.0,576.93,0.00,576.93,0.0
2,3,2025-04-21,Salas,NaN,cliente_003,NaT,NaT,BANQUETE,11.0,455.27,0.00,455.27,0.0
3,4,2025-10-24,Salas,NaN,cliente_004,NaT,NaT,REUNIÓN,15.0,0.00,0.00,0.00,0.0
4,5,2025-03-15,Salas,NaN,cliente_005,NaT,NaT,BANQUETE,14.0,438.97,25.08,413.89,0.0

In [63]:

((df['total_evento'] == 0) & (df['estado'] == 'CONFIRMACIÓN')).sum()

np.int64(12)

In [64]:
df[(df['total_evento'] == 0) & (df['estado'] == 'CONFIRMACIÓN')]

,id_booking,fecha_inicio,producto,estado,cliente,fecha_fin,fecha_creacion,tipo_evento,pax,total_evento,sala,fb,alojamiento
179,18437,2025-02-05,Salas,CONFIRMACIÓN,GENERICO GENERICO,2025-02-05,2025-01-22,REUNIÓN,46.0,0.0,0.0,0.0,0.0
242,19775,2025-03-26,Salas,CONFIRMACIÓN,cliente_033,2025-04-11,2025-02-18,REUNIÓN,70.0,0.0,0.0,0.0,0.0
296,21563,2025-03-24,Salas,CONFIRMACIÓN,cliente_041,2025-03-24,2025-03-24,BANQUETE,3.0,0.0,0.0,0.0,0.0
345,22444,2025-04-15,Salas,CONFIRMACIÓN,cliente_047,2025-04-15,2025-04-15,BANQUETE,9.0,0.0,0.0,0.0,0.0
381,23426,2025-05-15,Salas,CONFIRMACIÓN,cliente_053,2025-05-15,2025-05-15,REUNIÓN,16.0,0.0,0.0,0.0,0.0
383,23449,2025-05-16,Salas,CONFIRMACIÓN,cliente_053,2025-05-16,2025-05-16,BANQUETE,10.0,0.0,0.0,0.0,0.0
426,25481,2025-07-24,Salas,CONFIRMACIÓN,cliente_018,2025-07-24,2025-07-16,REUNIÓN,5.0,0.0,0.0,0.0,0.0
510,27904,2025-11-25,Salas,CONFIRMACIÓN,"GENERICO, EMPRESAS",2025-11-25,2025-09-25,REUNIÓN,25.0,0.0,0.0,0.0,0.0
568,28679,2025-10-13,Salas,CONFIRMACIÓN,cliente_026,2025-10-13,2025-10-13,BANQUETE,9.0,0.0,0.0,0.0,0.0
599,29191,2025-11-17,Salas,CONFIRMACIÓN,GENERICO GENERICO,2025-11-17,2025-10-27,REUNIÓN,20.0,0.0,0.0,0.0,0.0
617,29510,2025-11-13,Salas,CONFIRMACIÓN,"GENERICO, EMPRESAS",2025-11-13,2025-11-04,REUNIÓN,25.0,0.0,0.0,0.0,0.0
696,30780,2025-12-13,Salas,CONFIRMACIÓN,GENERICO GENERICO,2025-12-13,2025-12-10,COCKTAIL,130.0,0.0,0.0,0.0,0.0

In [65]:
df['estado'] = df['estado'].fillna('CONFIRMACIÓN')

In [66]:
df.head()

,id_booking,fecha_inicio,producto,estado,cliente,fecha_fin,fecha_creacion,tipo_evento,pax,total_evento,sala,fb,alojamiento
0,1,2025-02-22,Salas,CONFIRMACIÓN,cliente_001,NaT,NaT,BANQUETE,19.0,786.38,0.00,786.38,0.0
1,2,2025-05-10,Salas,CONFIRMACIÓN,cliente_002,NaT,NaT,BANQUETE,19.0,576.93,0.00,576.93,0.0
2,3,2025-04-21,Salas,CONFIRMACIÓN,cliente_003,NaT,NaT,BANQUETE,11.0,455.27,0.00,455.27,0.0
3,4,2025-10-24,Salas,CONFIRMACIÓN,cliente_004,NaT,NaT,REUNIÓN,15.0,0.00,0.00,0.00,0.0
4,5,2025-03-15,Salas,CONFIRMACIÓN,cliente_005,NaT,NaT,BANQUETE,14.0,438.97,25.08,413.89,0.0

In [67]:
df['antelacion_dias'] = (df['fecha_inicio'] - df['fecha_creacion']).dt.days

In [68]:
df.head()

,id_booking,fecha_inicio,producto,estado,cliente,fecha_fin,fecha_creacion,tipo_evento,pax,total_evento,sala,fb,alojamiento,antelacion_dias
0,1,2025-02-22,Salas,CONFIRMACIÓN,cliente_001,NaT,NaT,BANQUETE,19.0,786.38,0.00,786.38,0.0,NaN
1,2,2025-05-10,Salas,CONFIRMACIÓN,cliente_002,NaT,NaT,BANQUETE,19.0,576.93,0.00,576.93,0.0,NaN
2,3,2025-04-21,Salas,CONFIRMACIÓN,cliente_003,NaT,NaT,BANQUETE,11.0,455.27,0.00,455.27,0.0,NaN
3,4,2025-10-24,Salas,CONFIRMACIÓN,cliente_004,NaT,NaT,REUNIÓN,15.0,0.00,0.00,0.00,0.0,NaN
4,5,2025-03-15,Salas,CONFIRMACIÓN,cliente_005,NaT,NaT,BANQUETE,14.0,438.97,25.08,413.89,0.0,NaN

In [72]:
df.tail()

,id_booking,fecha_inicio,producto,estado,cliente,fecha_fin,fecha_creacion,tipo_evento,pax,total_evento,sala,fb,alojamiento,antelacion_dias
694,30700,2025-12-17,Salas,Perdido,"GENERICO, AGENCIAS",2025-12-17,2025-12-09,NaN,NaN,0.00,0.00,0.0,0.0,8.0
695,30766,2025-12-16,Salas,Perdido,GENERICO GENERICO,2025-12-16,2025-12-11,NaN,NaN,0.00,0.00,0.0,0.0,5.0
696,30780,2025-12-13,Salas,CONFIRMACIÓN,GENERICO GENERICO,2025-12-13,2025-12-10,COCKTAIL,130.0,0.00,0.00,0.0,0.0,3.0
697,30910,2025-12-24,Salas,CONFIRMACIÓN,cliente_120,2025-12-24,2025-12-16,BANQUETE,20.0,790.15,790.15,0.0,0.0,8.0
698,31180,2025-12-26,Salas,CONFIRMACIÓN,cliente_121,2025-12-26,2025-12-26,BANQUETE,38.0,1584.44,1584.44,0.0,0.0,0.0

In [77]:
df['estado'].value_counts()

estado
Perdido         412
CONFIRMACIÓN    263
Cancelado        24
Name: count, dtype: int64

In [74]:
df['estado'] = df['estado'].replace('Rechazado', 'Perdido')
df = df.drop(columns='cliente')

In [75]:
df.head()

,id_booking,fecha_inicio,producto,estado,fecha_fin,fecha_creacion,tipo_evento,pax,total_evento,sala,fb,alojamiento,antelacion_dias
0,1,2025-02-22,Salas,CONFIRMACIÓN,NaT,NaT,BANQUETE,19.0,786.38,0.00,786.38,0.0,NaN
1,2,2025-05-10,Salas,CONFIRMACIÓN,NaT,NaT,BANQUETE,19.0,576.93,0.00,576.93,0.0,NaN
2,3,2025-04-21,Salas,CONFIRMACIÓN,NaT,NaT,BANQUETE,11.0,455.27,0.00,455.27,0.0,NaN
3,4,2025-10-24,Salas,CONFIRMACIÓN,NaT,NaT,REUNIÓN,15.0,0.00,0.00,0.00,0.0,NaN
4,5,2025-03-15,Salas,CONFIRMACIÓN,NaT,NaT,BANQUETE,14.0,438.97,25.08,413.89,0.0,NaN

# GUARDAR DF LIMPIOS

In [78]:
df.to_csv('eventos_facturacion_limpio.csv', index=False)
precios_habs.to_csv('precios_habs_limpio.csv', index=False)
congresos.to_csv('congresos_limpio.csv', index=False)